# Generated by Django 4.2.7 on 2023-12-20 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
