# Generated by Django 4.2.7 on 2023-12-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_userfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="embedding_file",
            field=models.FileField(default=True, upload_to="embedding_files/"),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(upload_to="company_data_files/"),
        ),
    ]
