# Generated by Django 4.2.7 on 2023-12-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_userfile_embedding_file_alter_userfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="embedding_file",
            field=models.FileField(
                default=True, null=True, upload_to="embedding_files/"
            ),
        ),
    ]
