# Generated by Django 4.2.7 on 2023-12-26 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_userfile_embedding_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfile",
            name="embedding_file",
        ),
    ]
