# Generated by Django 5.0 on 2023-12-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_remove_userfile_embedding_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="embedding_file",
            field=models.FileField(
                default=True, null=True, upload_to="embedding_files/"
            ),
        ),
    ]
