# Generated by Django 5.0 on 2023-12-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_userfile_embedding_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="embedding_file",
            field=models.FileField(blank=True, null=True, upload_to="embedding_files/"),
        ),
    ]
