# Generated by Django 5.0 on 2023-12-27 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_userfile_embedding_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserFile",
            new_name="CompanyFile",
        ),
    ]
