# Generated by Django 5.0 on 2023-12-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_rename_userfile_companyfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyfile",
            name="file",
            field=models.FileField(upload_to="media/company_data_files/"),
        ),
    ]
