# Generated by Django 5.0 on 2023-12-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_alter_companyfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyfile",
            name="file",
            field=models.FileField(upload_to="company_data_files/"),
        ),
    ]
