# Generated by Django 4.2.7 on 2023-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("location", models.CharField(blank=True, max_length=140, null=True)),
                ("number", models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
