# Generated by Django 4.2.7 on 2023-12-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
