# Generated by Django 4.2.7 on 2023-12-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_client_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="client",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
