# Generated by Django 4.2.7 on 2023-12-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_client_age_client_gender_alter_client_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="emial",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
