# Generated by Django 4.2.7 on 2023-12-20 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_client_emial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="emial",
            new_name="email",
        ),
    ]
