# Generated by Django 4.2.7 on 2023-12-21 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_uploadedarchive"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedArchive",
        ),
    ]
