# Generated by Django 5.0 on 2023-12-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mainphoto",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
