# Generated by Django 5.0 on 2023-12-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_post_mainphoto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="contents",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="mainphoto",
        ),
        migrations.RemoveField(
            model_name="post",
            name="postname",
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Default Title", max_length=200),
        ),
    ]
