# Generated by Django 4.2.7 on 2023-12-28 04:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0009_recomment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recomment",
        ),
    ]
